layers/urls.py
from django.conf.urls import patterns, url
from layers import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'calculate/$', views.calculate, name='calculate'),
    url(r'^(?P<layer_slug>[\w\-]+)/$', views.detail, name='detail'),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'signin/$', 'django.contrib.auth.views.login',
            {'template_name':'users/signin.html'}, name='signin'),
    url(r'signout/$', 'django.contrib.auth.views.logout',
            {'next_page': '/'}, name='signout'),
)

webandgis/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^layers/', include('layers.urls', namespace='layers')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.dispatch import receiver
from django.conf import settings
from django.contrib.gis.gdal import DataSource
from django.template.defaultfilters import slugify
import zipfile
import os, errno
import glob

class Layer(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(editable=False)
    bbox = models.CharField(max_length=255, null=True, blank=True)
    original = models.FileField(upload_to='uploads', null=True, blank=True,
                                help_text="""Zip file with either geotiff and
                                        projection or shapefiles and friends""")
#    type = models.CharField(max_length=255)
    style = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.name)
        super(Layer, self).save(force_insert, force_update)

def create_folder(path):
    try:
        os.makedirs(path)
    except OSError as exc: # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else: raise

@receiver(models.signals.pre_save, sender=Layer)
def layer_handler(sender, instance, *args, **kwargs):
    """
    Post process the uploaded layer
    Get the bounding box information and save it with the model
    """

    instance.slug = slugify(instance.name)

    # Make a folder with the slug name
    # and create a 'raw' subdirectory to hold the files
    layer_folder = os.path.join(settings.MEDIA_ROOT, 'layers', instance.slug)
    create_folder(layer_folder)
    zip_out = os.path.join(layer_folder, 'raw')
    create_folder(zip_out)

    # Iterate over the files in the zip and create them in the raw folder.
    z = zipfile.ZipFile(instance.original)
    for name in z.namelist():
        outfile = open(os.path.join(zip_out, name), 'wb')
        outfile.write(z.read(name))
        outfile.close()

    # Check if it is vector or raster
    # if it has a .shp file, it is vector :)
    os.chdir(zip_out)
    shapefiles = glob.glob('*.shp')

    if len(shapefiles) > 0:
        # this means it is a vector

        # FIXME(This is a very weak way to get the shapefile)
        shapefile = shapefiles[0]

        # Use ogr to inspect the file and get the bounding box
        ds = DataSource(shapefile)
        layer = ds[0]
        extent = layer.extent.tuple
        instance.bbox = ",".join(["%s" % x for x in extent])

    # Render the tiles (if possible)

layers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from layers.models import Layer
from django.conf import settings
from safe.api import read_layer
from safe.api import calculate_impact
from safe.impact_functions.inundation.flood_OSM_building_impact import FloodBuildingImpactFunction
from subprocess import call
import glob
import os
from django.contrib.auth.decorators import login_required

def index(request):
    layers = Layer.objects.all()
    context = { 'layers': layers }
    return render(request, 'layers/index.html', context)

def detail(request, layer_slug):
    layer = get_object_or_404(Layer, slug=layer_slug)
    return render(request, 'layers/detail.html', {'layer': layer})

def get_layer_data(layer_name):
     layer = Layer.objects.get(name=layer_name)
     layer_path = os.path.join(settings.MEDIA_ROOT, 'layers', layer.slug, 'raw')
     os.chdir(layer_path)
     filename = glob.glob('*.shp')[0]
     layer_file = os.path.join(layer_path, filename)
     return read_layer(layer_file)

@login_required(redirect_field_name='next')
def calculate(request):
    """Calculates the buildings affected by flood.
    """

    output = os.path.join(settings.MEDIA_ROOT, 'layers', 'impact.json')

    buildings = get_layer_data('Buildings')
    flood = get_layer_data('Flood')

    # assign the required keywords for inasafe calculations
    buildings.keywords['category'] = 'exposure'
    buildings.keywords['subcategory'] = 'structure'
    flood.keywords['category'] = 'hazard'
    flood.keywords['subcategory'] = 'flood'

    impact_function = FloodBuildingImpactFunction
    # run analisys
    impact_file = calculate_impact(layers=[buildings, flood], impact_fcn=impact_function)


    call(['ogr2ogr', '-f', 'GeoJSON',
          output, impact_file.filename])

    impact_geojson = os.path.join(settings.MEDIA_URL, 'layers', 'impact.json')

    context = impact_file.keywords
    context['geojson'] = impact_geojson
    context['user'] = request.user

    return render(request, 'layers/calculate.html', context)

users/views.py
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django import forms

@csrf_exempt
def signin(request):
    username = password = ''
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')

    return render_to_response('users/signin.html')

def signout(request):
    logout(request)
    return HttpResponseRedirect('/')

layers/templates/layers/calculate.html
{% extends "site_base.html" %}
{% load leaflet_tags %}

{% block body %}

<h1>{{ map_title }}</h1>

<p>
    <a href={{ geojson }}>Download layer in GeoJSON format</a>
</p>

{% leaflet_map "layermap" %}

<p>{{ impact_summary|safe }}</p>

{% endblock %}

{% block extra_script %}
    {% leaflet_js %}
    {% leaflet_css %}
    <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.1.3"></script>
    <script type="text/javascript">
        function layermapInit(map, bounds) {
            var stamen = new L.StamenTileLayer("watercolor");
            stamen.addTo(map);

            // Pulls GeoJSON data and adds layer to the basemap
            $.getJSON('{{ geojson }}', function(geojsonFeature){
                var myLayer = L.geoJson().addTo(map);
                myLayer.addData(geojsonFeature);

                // Zooms map to geoJSON layer's bounds
                map.fitBounds(myLayer.getBounds());
			});
        }
    </script>
{% endblock %}

layers/templates/layers/detail.html
{% extends "site_base.html" %}
{% load leaflet_tags %}

{% block body %}

<h1>{{ layer.name }}</h1>

<p>{{ layer.description }}</p>

{% leaflet_map "layermap" %}

{% endblock %}

{% block extra_script %}
    {% leaflet_js %}
    {% leaflet_css %}
    <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.1.3"></script>
    <script type="text/javascript">
        function layermapInit(map, bounds) {
            var stamen = new L.StamenTileLayer("watercolor");
            stamen.addTo(map);

            var bbox = [{{ layer.bbox }}];
            var bounds = [[bbox[1], bbox[0]], [bbox[3], bbox[2]]];
            map.fitBounds(bounds);
            var polygon = L.polygon([
                            [bbox[1], bbox[0]],
    		                [bbox[3], bbox[0]],
                            [bbox[3], bbox[2]],
                            [bbox[1], bbox[2]],
                          ]).addTo(map);
        }
    </script>
{% endblock %}

layers/templates/layers/index.html
{% extends "site_base.html" %}

{% block body %}
<h2>Layers</h2>
{% if layers %}
    <ul>
    {% for layer in layers %}
        <li><a href="{% url 'layers:detail' layer.slug %}">{{ layer.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No layers are available.</p>
{% endif %}

{% endblock %}

users/templates/users/signin.html
{% extends "site_base.html" %}

{% block body %}

<form class="form-horizontal" action="/users/signin/" method="post">{% csrf_token %}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
    {% endif %}

    {% if form.errors %}
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Your username and password didn't match.</strong>
        </div>
    {% endif %}


    <div class="control-group">
        <label class="control-label" for="inputUsername">Username</label>
        <div class="controls">
            <input type="text" id="inputUsername" name="username"
                value="{{ username }}" placeholder="Username">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputPassword">Password</label>
        <div class="controls">
            <input type="password" id="inputPassword" name="password"
                value="" placeholder="Password">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <label class="checkbox">
                <input type="checkbox"> Remember me
            </label>
            <button type="submit" class="btn">Sign in</button>
        </div>
    </div>
</form>

{% endblock %}

webandgis/templates/_account_bar.html
<ul class="nav nav-pills">
    <li><a href="/">Home</a></li>
    <li><a href="{% url 'layers:index' %}">Layers</a></li>
</ul>

{% if not user.is_authenticated %}
    <h4 class="pull-right">
        <a href="#">Sign-up</a> |
        <a href="{% url 'users:signin' %}">Sign-in</a>
    </h4>
{% else %}
    <h4 class="pull-right">
        Welcome {{ user.username.capitalize }}! |
        <a href="{% url 'users:signout' %}">Sign-out</a>
    </h4>
{% endif %}

<script>
    String.prototype.rsplit = function(sep, maxsplit) {
        var split = this.split(sep);
        return maxsplit ? [ split.slice(0, -maxsplit).join(sep) ].
                                concat(split.slice(-maxsplit)) : split;
    }

    resource = document.location.pathname.rsplit('/',-2);
    if (resource.length > 1) resource = resource[0] + '/';
    $('ul.nav > li > a[href="' + resource + '"]').parent().addClass('active');
</script>

webandgis/templates/_footer.html
{% load i18n %}
<div class="legal">
    {% trans "This is the footer" %}
</div>

webandgis/templates/homepage.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h1>{% trans "Web and GIS" %}</h1>
    <p>
        {% blocktrans %}
         Check out the <a href="/layers">Layers</a> we have!
        {% endblocktrans %}
    </p>
{% endblock %}

webandgis/templates/site_base.html
{% extends "theme_base.html" %}

{% load i18n %}

{% block extra_head_base %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
    {% block extra_head %}{% endblock %}
{% endblock %}

{% block footer %}
    {% include "_footer.html" %}
{% endblock %}

{% block extra_body_base %}
    {% block extra_body %}{% endblock %}
{% endblock %}